start: motion (";" motion)*

motion: "[" INT "," INT "]" sensor ("*" sensor)*

sensor: JOINT "." AXIS "(" REAL ")"

JOINT: "pelvis" | "torso" | "spine" | "chest" | "neck" | "head"
    | "lhip" | "lknee" | "lankle" | "ltoe"
    | "rhip" | "rknee" | "rankle" | "rtoe"
    | "lthorax" | "lshoulder" | "lelbow" | "lwrist" | "lhand"
    | "rthorax" | "rshoulder" | "relbow" | "rwrist" | "rhand"

AXIS: "x" | "y" | "z"

INT: /[0-9]+/

REAL: /-?[0-9]+\.[0-9]+/


