[project]
name = "exact"
version = "0.1.0"
description = "Executable Activity Models"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dlc2action",
    "edist>=1.2.0",
    "h5py",
    "hydra-core>=1.3.0",
    "lark>=1.3.1",
    "loguru>=0.7.3",
    "matplotlib>=3.7.0",
    "mediapy>=1.2.5",
    "metamotivo[all]",
    "numpy",
    "omegaconf>=2.3.0",
    "pandas",
    "peft>=0.8.0",
    "scikit-learn>=1.3.0",
    "syncode>=0.4.16",
    "torch",
    "tqdm",
    "transformers>=4.30.0",
    "wandb>=0.16.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "ipywidgets>=8.1.8",
    "notebook>=7.4.7",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:__array_wrap__ must accept context and return_scalar arguments:DeprecationWarning:dm_control.utils.rewards",
    "ignore:__array__ implementation doesn't accept a copy keyword:DeprecationWarning:metamotivo.wrappers.humenvbench"
]


[tool.uv.sources]
metamotivo = { git = "https://github.com/facebookresearch/metamotivo.git" }
dlc2action = {git = "https://github.com/amathislab/DLC2action.git"}

[tool.setuptools.package-dir]
exact = "exact"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
