[project]
name = "exact"
version = "0.1.0"
description = "Learning and Reasoning with Executable Activity Models"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipywidgets>=8.1.7",
    "lightning>=2.5.2",
    "mediapy>=1.2.4",
    "metamotivo[all]",
    "notebook>=7.4.7",
    "pot>=0.9.5",
    "syncode>=0.4.16",
]

[tool.uv.sources]
metamotivo = { git = "https://github.com/facebookresearch/metamotivo.git" }

[tool.setuptools.package-dir]
exact = "exact"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
